import type { Metadata } from 'next'
import { Geist, Geist_Mono, Inter } from 'next/font/google'
import '@/styles/globals.css'
import Modal from '@/components/modal/Modal'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
  // weight: ['400', '500', '600', '700'],
})

export const metadata: Metadata = {
  title: 'chatbox',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${geistMono.variable} ${geistSans.variable} antialiased bg-gradient-main h-screen`}
      >
        {children}
        <Modal />
      </body>
    </html>
  )
}
